export const FREE_PLAN_MAX_TEAM_LIMIT = 1
export const FREE_PLAN_MAX_CLUSTER_LIMIT = 1

export const FREE_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION = 1
export const FREE_PLAN_MAX_ROWS_READ_IN_MONTH =
  FREE_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION * 1e9

export const FREE_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION = 10
export const FREE_PLAN_MAX_ROWS_WRITE_IN_MONTH =
  FREE_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION * 1e6

export const FREE_PLAN_MAX_STORAGE_LIMIT_GB = 5
export const FREE_PLAN_MAX_STORAGE_LIMIT_BYTE =
  FREE_PLAN_MAX_STORAGE_LIMIT_GB * 1e9

export const FREE_PLAN_MAX_BRANCH_LIMIT = 2

// --------------------------------------------------------

export const STARTER_PLAN_MAX_TEAM_LIMIT = 3
export const STARTER_PLAN_MAX_CLUSTER_LIMIT = 3

export const STARTER_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION = 10
export const STARTER_PLAN_MAX_ROWS_READ_IN_MONTH =
  STARTER_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION * 1e9

export const STARTER_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION = 100
export const STARTER_PLAN_MAX_ROWS_WRITE_IN_MONTH =
  STARTER_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION * 1e6

export const STARTER_PLAN_MAX_STORAGE_LIMIT_GB = 50
export const STARTER_PLAN_MAX_STORAGE_LIMIT_BYTE =
  STARTER_PLAN_MAX_STORAGE_LIMIT_GB * 1e9

export const STARTER_PLAN_MAX_BRANCH_LIMIT = 5

// --------------------------------------------------------

export const PRO_PLAN_MAX_TEAM_LIMIT = Infinity
export const PRO_PLAN_MAX_CLUSTER_LIMIT = Infinity

export const PRO_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION = Infinity
export const PRO_PLAN_MAX_ROWS_READ_IN_MONTH =
  PRO_PLAN_MAX_ROWS_READ_IN_MONTH_BILLION * 1e9

export const PRO_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION = Infinity
export const PRO_PLAN_MAX_ROWS_WRITE_IN_MONTH =
  PRO_PLAN_MAX_ROWS_WRITE_IN_MONTH_MILLION * 1e6

export const PRO_PLAN_MAX_STORAGE_LIMIT_GB = Infinity
export const PRO_PLAN_MAX_STORAGE_LIMIT_BYTE =
  PRO_PLAN_MAX_STORAGE_LIMIT_GB * 1e9

export const PRO_PLAN_MAX_BRANCH_LIMIT = Infinity
