name: Wraith CI
description: GitHub Action for Wraith CI

inputs:
  payload:
    description: Octoflare Payload
    required: true
  data:
    description: Wraith CI Payload
    required: true

runs:
  using: node20
  main: packages/action/dist/index.cjs
