name: Wraith CI
description: GitHub Action for Wraith CI

inputs:
  payload:
    description: Wraith Payload
    required: true
  name:
    description: Ghost App Name
    required: true

runs:
  using: node20
  main: packages/action/dist/index.cjs
