name: CI

on: push

jobs:
  test:
    uses: jill64/.github/.github/workflows/run-vitest.yml@main
    with:
      monorepo: 'true'
  test-e2e:
    uses: jill64/.github/.github/workflows/run-playwright.yml@main
