name: Wraith CI

on:
  workflow_dispatch:
    inputs:
      payload:
        required: true

env:
  GH_TOKEN: ${{ fromJson(inputs.payload).token }}
  repository: ${{ fromJson(inputs.payload).owner }}/${{ fromJson(inputs.payload).repo }}
  ref: ${{ fromJson(inputs.payload).data.ref }}

jobs:
  wraith-ci:
    strategy:
      fail-fast: false
      matrix:
        name: ['build', 'lint', 'format', 'deploy', 'release']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ env.repository }}
          ref: ${{ env.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            recursive: true

      - name: Ghost ${{ matrix.name }}
        uses: jill64/wraith-ci@main
        with:
          payload: ${{ inputs.payload }}
          name: ${{ matrix.name }}
          run_attempt: ${{ github.run_attempt }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ matrix.name == 'deploy' && secrets.CLOUDFLARE_API_TOKEN }}
          NODE_AUTH_TOKEN: ${{ matrix.name == 'release' && secrets.NPM_TOKEN }}

          X_EN_APP_KEY: ${{ matrix.name == 'release' && secrets.X_EN_API_KEY }}
          X_EN_APP_SECRET: ${{ matrix.name == 'release' && secrets.X_EN_API_SECRET }}
          X_EN_ACCESS_TOKEN: ${{ matrix.name == 'release' && secrets.X_EN_ACCESS_TOKEN }}
          X_EN_ACCESS_SECRET: ${{ matrix.name == 'release' && secrets.X_EN_ACCESS_SECRET }}

          X_JP_APP_KEY: ${{ matrix.name == 'release' && secrets.X_JP_API_KEY }}
          X_JP_APP_SECRET: ${{ matrix.name == 'release' && secrets.X_JP_API_SECRET }}
          X_JP_ACCESS_TOKEN: ${{ matrix.name == 'release' && secrets.X_JP_ACCESS_TOKEN }}
          X_JP_ACCESS_SECRET: ${{ matrix.name == 'release' && secrets.X_JP_ACCESS_SECRET }}

  try-fix-lock:
    needs: wraith-ci
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ env.repository }}
          ref: ${{ env.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20

      - name: Delete pnpm-lock.yaml
        run: rm -f pnpm-lock.yaml

      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            recursive: true

      - name: Staging
        run: git add pnpm-lock.yaml

      - name: Push
        run: |
          if [ $(git diff --cached --name-only) ]; then
            git commit -m "fix: invalid pnpm-lock.yaml"
            git pull --rebase
            git push origin
          fi

  post-process:
    needs: [try-fix-lock, wraith-ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Close Check Run
        run: |
          gh api \
            --method PATCH \
            /repos/${{ env.repository }}/check-runs/${{ fromJson(inputs.payload).data.check_run_id }} \
            --field status=completed \
            --field conclusion=${{ needs.wraith-ci.result }}

      - name: Revoke Installation Token
        run: gh api --method DELETE /installation/token

      - name: Revoke App Token
        run: gh api --method DELETE /installation/token
        env:
          GH_TOKEN: ${{ fromJson(inputs.payload).app_token }}
