name: Wraith CI

on:
  workflow_dispatch:
    inputs:
      payload:
        required: true

env:
  GH_TOKEN: ${{ fromJson(inputs.payload).token }}

jobs:
  wraith-ci:
    strategy:
      fail-fast: false
      matrix:
        name: ['build', 'lint', 'format', 'deploy', 'release']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ fromJson(inputs.payload).owner }}/${{ fromJson(inputs.payload).repo }}
          ref: ${{ fromJson(inputs.payload).ref }}

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Ghost ${{ matrix.name }}
        uses: jill64/wraith-ci@main
        with:
          payload: ${{ inputs.payload }}
          name: ${{ matrix.name }}
        env:
          PUBLIC_SENTRY_DSN: ''
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

          X_EN_APP_KEY: ${{ secrets.X_EN_API_KEY }}
          X_EN_APP_SECRET: ${{ secrets.X_EN_API_SECRET }}
          X_EN_ACCESS_TOKEN: ${{ secrets.X_EN_ACCESS_TOKEN }}
          X_EN_ACCESS_SECRET: ${{ secrets.X_EN_ACCESS_SECRET }}

          X_JP_APP_KEY: ${{ secrets.X_JP_API_KEY }}
          X_JP_APP_SECRET: ${{ secrets.X_JP_API_SECRET }}
          X_JP_ACCESS_TOKEN: ${{ secrets.X_JP_ACCESS_TOKEN }}
          X_JP_ACCESS_SECRET: ${{ secrets.X_JP_ACCESS_SECRET }}

  revoke-installation-token:
    needs: wraith-ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Revoke token
        run: gh api --method DELETE /installation/token

  revoke-app-token:
    needs: wraith-ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Revoke token
        run: gh api --method DELETE /installation/token
        env:
          GH_TOKEN: ${{ fromJson(inputs.payload).app_token }}
