name: Wraith CI

on:
  workflow_dispatch:
    inputs:
      payload:
        required: true
      data:
        required: true

jobs:
  wraith-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ fromJson(inputs.payload).token }}
          repository: ${{ fromJson(inputs.payload).owner }}/${{ fromJson(inputs.payload).repo }}

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20

      - name: Wraith CI
        uses: jill64/wraith-ci@main
        with:
          payload: ${{ inputs.payload }}
          data: ${{ inputs.data }}
        env:
          PUBLIC_SENTRY_DSN: ''
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
